In [50]:
import matplotlib.pyplot as plt
import math
import time
import random
import copy

import numpy as np
import copy
import torch
import cv2

In [58]:
class Agent_Conv:
    def __init__(self, num_input, layers, num_output):
        assert type(layers)==type([]), "Error with layers, give array of the number of layers"
        self.num_input = num_input  #set input number
        self.num_output = num_output #set ooutput number
        self.hidden=[]
        last=num_input
        self.num_genes=0
        for layer in layers:
            self.hidden.append(layer)
            self.num_genes+=(last * layer)
            last=layer
        self.num_genes +=(self.hidden[-1]*num_output)+num_output
        self.weights = None
        self.hidden_weights=None
        self.bias = None
        print("Auto",self.num_genes)
    def set_genes(self, gene):
        weight_idxs = self.num_input * self.hidden[0] #size of weights to hidden
        current=weight_idxs
        weights_idxs=[current] #start with end of last
        for i in range(len(self.hidden)-1):
            current+=self.hidden[i]*self.hidden[i+1] #calculate next idx for each layer
            weights_idxs.append(current)
        bias_idxs=None
        weights_idxs.append(self.hidden[-1] * self.num_output + weights_idxs[-1]) #add last layer heading to output
        bias_idxs = weights_idxs[-1]+ self.num_output #sizes of biases
        w = gene[0 : weight_idxs].reshape(self.hidden[0], self.num_input)   #merge genes
        ws=[]
        for i in range(len(self.hidden)-1):
            ws.append(gene[weights_idxs[i] : weights_idxs[i+1]].reshape(self.hidden[i+1], self.hidden[i]))
        ws.append(gene[weights_idxs[-2] : weights_idxs[-1]].reshape(self.num_output, self.hidden[-1]))
        b = gene[weights_idxs[-1]: bias_idxs].reshape(self.num_output,) #merge genes

        self.weights = torch.from_numpy(w) #assign weights
        self.hidden_weights=[]
        for w in ws:
            self.hidden_weights.append(torch.from_numpy(w))
        self.bias = torch.from_numpy(b) #assign biases

    def forward(self, x):
        #create conv layer
        print(len(self.weights))
        m=torch.nn.Conv2d(1, len(self.weights), kernel_size=7, stride=2, padding=3, bias=False)
        print(x.shape)
        x=m(torch.tensor(x))
        H=len(x)
        x = torch.tensor(np.dot(self.weights.T.float(),x.detach().numpy()).flatten())
        #run through forward layers
        x = torch.mm(x.reshape(1,H), self.weights.T.float()) #first layer
        for i in range(len(self.hidden_weights)-1):
            x =torch.mm(x,self.hidden_weights[i].T.float()) #second layer
        return torch.mm(x,self.hidden_weights[-1].T.float()) + self.bias #third layer
    
    def get_action(self, x):
        vectors=[(1,1),(1,0),(0,1),(-1,-1),(-1,0),(0,-1),(-1,1),(1,-1)] #possible moves
        arr=list(self.forward(x)[0])
        ind=np.argmax(arr)
        return vectors[ind]

In [59]:
whegBot=Agent_Conv(5*5,[10,10],10) #define the agent


input_=np.random.rand(5,5)
output_=np.random.rand(10)

whegBot.set_genes(np.random.normal(0, 0.5, (whegBot.num_genes)))
print(input_)

whegBot.get_action(input_)

Auto 460
[[0.0133354  0.30467209 0.95126865 0.41333243 0.2801577 ]
 [0.63529326 0.23482043 0.95210202 0.49279534 0.92566267]
 [0.38065973 0.0540948  0.36825895 0.57131332 0.98347282]
 [0.83797445 0.0504508  0.90644625 0.1939965  0.07766266]
 [0.02393758 0.84156432 0.93992092 0.38372223 0.84278428]]
(5, 5)


RuntimeError: Expected 4-dimensional input for 4-dimensional weight [10, 1, 7, 7], but got 2-dimensional input of size [5, 5] instead